module.exports = {
  head: `<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="mobile-web-app-capable" content="yes"/><script>!function(e,t,a,n,g){e[n]=e[n]||[],e[n].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});var m=t.getElementsByTagName(a)[0],r=t.createElement(a);r.async=!0,r.src="https://www.googletagmanager.com/gtm.js?id=GTM-PVRTWJK",m.parentNode.insertBefore(r,m)}(window,document,"script","dataLayer")</script>`,
  body: `<body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVRTWJK" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><noscript>If you're seeing this message, that means <strong>JavaScript has been disabled on your browser</strong>, please <strong>enable JS</strong> to make this app work.</noscript><div id="modal"></div><div id="app" class="stickyFooter"></div><script type="text/javascript" src="/runtime~main.f3bf2570e019d96acc37.js"></script><script type="text/javascript" src="/vendor.9131d7a74a3f7bf48a5e.chunk.js"></script><script type="text/javascript" src="/main.9d27f9846d3a299f25b5.chunk.js"></script></body></html>`,
  normal: `<title>Waft Engine</title><meta name="description" content="node nodejs react redux mongoose opensource open source free waftengine "/><link rel="icon" href="favicon.png" sizes="16x16" type="image/png"/><meta property="og:title" content="NEPAL OFFERS"/><meta property="og:type" content="website"/><meta property="og:image" content="/favicon.ico"/><meta name="theme-color" content="#5D524C"/><link rel="manifest" href="/manifest.a27c6f5fd23e37614de3064c0ca5a7a8.json"/></head>`,
  apiBaseUrl: 'http://localhost:5050/api',
  // apiBaseUrl: 'https://waftengine.org/api',
  // siteUrl: 'https://waftengine.org/',
  siteUrl: 'http://localhost:5050/',
};
