export const LOAD_VIDEODETAIL_REQUEST = 'app/VideoDetailPage/LOAD_VIDEODETAIL_REQUEST';
export const LOAD_VIDEODETAIL_SUCCESS = 'app/VideoDetailPage/LOAD_VIDEODETAIL_SUCCESS';
export const LOAD_VIDEODETAIL_FAILURE = 'app/VideoDetailPage/LOAD_VIDEODETAIL_FAILURE';
