export const LOAD_VIDEOLIBRARY_LIST_REQUEST = 'app/VideoLibraryListingPage/LOAD_VIDEOLIBRARY_LIST_REQUEST';
export const LOAD_VIDEOLIBRARY_LIST_SUCCESS = 'app/VideoLibraryListingPage/LOAD_VIDEOLIBRARY_LIST_SUCCESS';
export const LOAD_VIDEOLIBRARY_LIST_FAILURE = 'app/VideoLibraryListingPage/LOAD_VIDEOLIBRARY_LIST_FAILURE';
