module.exports = {
  validateFiscal: {
    InvalidFrom: 'Please input the date type data',
    InvalidTo: 'Please input the date type data',
    EmptyFiscalYear: 'Fiscalyear field is required',
    FiscalLength: 'Length of fiscal field should be between 4 to 10',
    FromLength: 'Length of from field should be between 3 to 4',
    ToLength: 'Length of to field should be between 3 to 4',
    EmptyFrom: 'From field is required',
    EmptyTo: 'To field is required',
    IsPhone: 'Invalid phone number',
    Uppercase: 'This Field should be in uppercase',
    IsAfter: 'Please enter the date of after 1971',
    IsEmail: 'Enter the email type data',
    IsURL: 'This field should be of url type',
    IsBoolean: 'This field requires boolean type data',
  },
  saveFiscal: 'Fiscals data saved successfully',
  getFiscals: 'Fiscals data obtained successfully',
  getFiscal: 'Fiscal data obtained successfully',
  deleteFiscal: 'Fiscal data deleted successfully',
};
