export const LOAD_BLOG_LIST_REQUEST = 'app/BlogList/LOAD_BLOG_LIST_REQUEST';
export const LOAD_BLOG_LIST_SUCCESS = 'app/BlogList/LOAD_BLOG_LIST_SUCCESS';
export const LOAD_BLOG_LIST_FAILURE = 'app/BlogList/LOAD_BLOG_LIST_FAILURE';
export const SET_PAGES_VALUE = 'app/BlogList/SET_PAGES_VALUE';
export const SET_QUERY_VALUE = 'app/BlogList/SET_QUERY_VALUE';
export const SET_SIZE_VALUE = 'app/BlogList/SET_SIZE_VALUE';
export const CLEAR_ALL = 'app/BlogList/CLEAR_ALL';

export const LOAD_BLOG_BY_AUTHOR_REQUEST =
  'app/BlogList/LOAD_BLOG_BY_AUTHOR_REQUEST';
export const LOAD_BLOG_BY_AUTHOR_SUCCESS =
  'app/BlogList/LOAD_BLOG_BY_AUTHOR_SUCCESS';
export const LOAD_BLOG_BY_AUTHOR_FAILURE =
  'app/BlogList/LOAD_BLOG_BY_AUTHOR_FAILURE';

export const LOAD_BLOG_BY_TAG_REQUEST = 'app/BlogList/LOAD_BLOG_BY_TAG_REQUEST';
export const LOAD_BLOG_BY_TAG_SUCCESS = 'app/BlogList/LOAD_BLOG_BY_TAG_SUCCESS';
export const LOAD_BLOG_BY_TAG_FAILURE = 'app/BlogList/LOAD_BLOG_BY_TAG_FAILURE';

export const LOAD_BLOG_DATE_REQUEST = 'app/BlogList/LOAD_BLOG_DATE_REQUEST';
export const LOAD_BLOG_DATE_SUCCESS = 'app/BlogList/LOAD_BLOG_DATE_SUCCESS';
export const LOAD_BLOG_DATE_FAILURE = 'app/BlogList/LOAD_BLOG_DATE_FAILURE';
