export const LOAD_BLOG_REQUEST = 'app/BlogPage/LOAD_BLOG_REQUEST';
export const LOAD_BLOG_SUCCESS = 'app/BlogPage/LOAD_BLOG_SUCCESS';
export const LOAD_BLOG_FAILURE = 'app/BlogPage/LOAD_BLOG_FAILURE';

export const LOAD_BLOG_BY_AUTHOR_REQUEST =
  'app/BlogPage/LOAD_BLOG_BY_AUTHOR_REQUEST';
export const LOAD_BLOG_BY_AUTHOR_SUCCESS =
  'app/BlogPage/LOAD_BLOG_BY_AUTHOR_SUCCESS';
export const LOAD_BLOG_BY_AUTHOR_FAILURE =
  'app/BlogPage/LOAD_BLOG_BY_AUTHOR_FAILURE';

export const LOAD_BLOG_BY_TAG_REQUEST = 'app/BlogPage/LOAD_BLOG_BY_TAG_REQUEST';
export const LOAD_BLOG_BY_TAG_SUCCESS = 'app/BlogPage/LOAD_BLOG_BY_TAG_SUCCESS';
export const LOAD_BLOG_BY_TAG_FAILURE = 'app/BlogPage/LOAD_BLOG_BY_TAG_FAILURE';

export const LOAD_RELATED_BLOGS_REQUEST =
  'app/BlogPage/LOAD_RELATED_BLOGS_REQUEST';
export const LOAD_RELATED_BLOGS_SUCCESS =
  'app/BlogPage/LOAD_RELATED_BLOGS_SUCCESS';
export const LOAD_RELATED_BLOGS_FAILURE =
  'app/BlogPage/LOAD_RELATED_BLOGS_FAILURE';

export const LOAD_RECENT_BLOGS_REQUEST =
  'app/BlogPage/LOAD_RECENT_BLOGS_REQUEST';
export const LOAD_RECENT_BLOGS_SUCCESS =
  'app/BlogPage/LOAD_RECENT_BLOGS_SUCCESS';
export const LOAD_RECENT_BLOGS_FAILURE =
  'app/BlogPage/LOAD_RECENT_BLOGS_FAILURE';
