export const LOAD_BLOG_LIST_REQUEST = 'app/BlogList/LOAD_BLOG_LIST_REQUEST';
export const LOAD_BLOG_LIST_SUCCESS = 'app/BlogList/LOAD_BLOG_LIST_SUCCESS';
export const LOAD_BLOG_LIST_FAILURE = 'app/BlogList/LOAD_BLOG_LIST_FAILURE';
