module.exports = {
    fieldType:{
        SingleLine:{
            name:"Single Name",
            label:"String",
            key:"String",
            required:"Bool",
            numberOfCharacter:"Number",
        },
        AutoNumberField:{
            name:"Auto-Number Field",
            label:"String",
            key:"String",
            required:"Bool",
            prefix:"String",
            startingNumber:"Number",
            suffix:"String",
        },
        MultiLine:{
            name:"Multi-Line",
            label:"String",
            key:"String",
            required:"Bool",
            numberOfCharacter:"Number"
        },
        Email:{
            name:"Email",
            label:"String",
            key:"String",
            required:"Bool",
            duplicate:"Bool"
        },
        Phone:{
            name:"Phone",
            label:"String",
            key:"String",
            required:"Bool",
            duplicate:"Bool"
        },
        PickList:{
            name:"Pick List",
            label:"String",
            key:"String",
            required:"Bool",
            option:"ArrayOfString",
            default:"String",
            type:"String"
        },
        MultiSelect:{
            name:"Multi-Select",
            label:"String",
            key:"String",
            required:"Bool",
            option:"ArrayOfString",
            default:"ArrayOfString",
            type:"ArrayOfString"
        },
        Date:{
            name:"Date",
            label:"String",
            key:"String",
            required:"Bool",
            type:"Date",
            default:"Date",
        },
        DateTime:{
            name:"Date/Time",
            label:"String",
            key:"String",
            required:"Bool",
            type:"DateTime",
            default:"DateTime",
        },
        Decimal:{
            name:"Decimal",
            label:"String",
            key:"String",
            required:"Bool",
            type:"Decimal",
            default:"Decimal",
            maxDigit:"Number", //16
            decimalPlace:"Number", //9
        },
        LongInteger:{
            name:"Long Integer",
            label:"String",
            key:"String",
            required:"Bool",
            type:"Number",
            default:"Number",
            maxDigit:"Number", //18
        },
        Checkbox:{
            name:"Checkbox",
            label:"String",
            type:"Bool",
            default:"Bool",
        },
        URL:{
            name:"URL",
            label:"String",
            key:"String",
            required:"Bool",
            type:"String",
        },
        Lookup:{
            name:"Lookup",
            label:"String",
            key:"String",
            required:"Bool",
            type:"Module,Id",
        },
        MultiSelectLookup:{
            name:"Multi-Select Lookup",
            label:"String",
            key:"String",
            required:"Bool",
            type:"Module,ArrayId",
        },
        User:{
            name:"User",
            label:"String",
            key:"String",
            required:"Bool",
            type:"User,Id",
        },
        FileUpload:{
            name:"File Upload",
            label:"String",
            key:"String",
            required:"Bool",
            minFile:"Number",
            maxFile:"Number",
            type:"File,ArrayId",
        }
    },
    section:{
        name:"String",
        key:"String",
        layout:["Single Column","Double Column"]
    }
  };
  