module.exports = {
  validationMessage: {
    nameRequired: 'I think you missed the Name field!!',
    nameInvalidLength: 'Sorry, Name must be atleast 5 characters',
    designationInvalid: 'Sorry, Designation must be a valid value!',
    emailInvalid: 'I think Email is Invalid!',
    emailRequired: 'Sorry, you missed the Email!!',
    passwordInvalidLength: 'Sorry, Password must be minimun 6 characters and maximum 30 characters!!!',
    passwordRequired: 'Sorry, Password is required!!!',
    password2Required: 'Please, reenter the Password',
    passwordMismatch: 'Sorry, your passwords do not match!!',
    stateInvalid: 'Sorry, State is invalid!!',
    districtInvalid: 'Sorry, District is invalid!!',
    vdcInvalid: 'Sorry, VDC/Municipality is invalid!!',
    emailExists: 'I am sure, that Email already exists!!!',
    rolesInvalid: 'Sorry, the Role you selected is invalid!!!',
    rolesRequired: 'Sorry, you missed the roles field!!',
    genderInvalid: 'Sorry, you entered an invalid Gender',
    genderRequired: 'Sorry, Gender is required!!!',
  },
};
