module.exports = {
  ValidationMessage: {
    NoOfDaysRequired: 'Must enter Numeric Value',
    NoOfDaysInvalid: 'Must be a number greater than 0',
    SubmittedToRequired: 'Submitted to must be entered',
    SubmittedToInvalid: 'Submitted to must be String',
    SubmittedByRequired: 'Submitted by must be entered',
    SubmittedByInvalid: 'Submitted by must be string',
    Added_byRequired: 'you can`t skip Added by',
    Added_byInvalid: 'Please try to spell in string',
    ToRequired: 'Please enter To Date',
    FromRequired: 'Please enter From Date',
    RemarkRequired: 'You must enter Remarks',
    StatusRequired: 'You must select Status',
    DateRequired: 'Please Enter in Standard Date format',
    UserIDRequired: 'Please use UserID',
    ToInvalid: 'Invalid Date!!!',
    FromInvalid: 'Invalid Date!!!',
    EmployIDRequired: 'Employee ID not found!!',
    EmployIDInvalid: 'Employee ID invalid!!!',
    LeaveTypeIDRequired: 'Leave type is required!!!',
    LeaveTypeIDInvalid: 'Leave type is Invalid!!!',

    GetLeaveApplication: 'Leave Application Data Delivered Successfully',
    AddLeaveApplication: 'Leave Application Saved Success !!',
    ValidationError: 'Leave ApplicationValidation Error!!',
    DuplicateStatus: 'Leave Conflicts with exisiting leave',
    ApplicationFailed: 'Leave Application Failed !!',
    DeleteByID: 'Leave Application Data delete Success',
    ToBefore: 'To date is before From date!!!',
    FromDateRequired: 'From date is not available',
    ToDateRequired: 'To date is not available',
    ToFromInvalid: 'To and From must belong to same fiscal year!!!',
    FetchFailed: 'No of days fetch Failed !!',
    FetchSuccess: 'No of days fetch Success',
  },
};
