module.exports = {
  ValidationMessage: {
    NoOfDaysRequired: 'Must enter Numeric Value',
    NoOfDaysInvalid: 'Must be a number and must be 1 or greater than 1',
    SubmittedToRequired: 'Submitted to must be entered',
    SubmittedToInvalid: 'Submitted to must be String',
    SubmittedByRequired: 'Submitted by must be entered',
    SubmittedByInvalid: 'Submitted by must be string',
    Added_byRequired: 'you can`t skip Added by',
    Added_byInvalid: 'Please try to spell in string',
    ToRequired: 'Please enter To Date',
    FromRequired: 'Please enter From Date',
    RemarkRequired: 'You must enter Remarks',
    StatusRequired: 'You must select Status',
    DateRequired: 'Please Enter in Standard Date format',
    UserIDRequired: 'Please use UserID',
    ToInvalid: 'Invalid Date!!!',
    FromInvalid: 'Invalid Date!!!',
    EmployIDRequired: 'Employee ID not found!!',
    EmployIDInvalid: 'Employee ID invalid!!!',
    LeaveTypeIDRequired: 'Leave type is required!!!',
    LeaveTypeIDInvalid: 'Leave type is Invalid!!!',
  },
};
